pipelines:
  branches:
    prod:
      - step:
          name: Trigger Jenkins Job and Wait for Result
          script:
            - |
              # Trigger Jenkins job
              curl -k -X GET https://af08-2406-b400-d11-a016-a07f-2ecf-3622-9d09.ngrok-free.app/generic-webhook-trigger/invoke?token=12345
              apt-get update && apt-get install -y jq

              # Poll for completion status from Jenkins (example loop)
              until [ "$(curl -sSf -k -u nihar:Maheshraval@11  https://af08-2406-b400-d11-a016-a07f-2ecf-3622-9d09.ngrok-free.app/job/test%20git/lastBuild/api/json -- | jq -r '.result')" != "null" ]; do
                echo "Waiting for Jenkins job to complete..."
                sleep 10  # Adjust the sleep duration as needed
              done

              # You might perform further actions based on the Jenkins job completion status
              # For example, echo a success message or handle errors
              echo "Jenkins job completed!"
          # Add retries, timeouts, or error handling as needed
